### ISSUE TITLE
Does not predictably handle redirect keys

### ISSUE THREAD

**Issue by shayypy** [timharek/openlibrary#1]
Hi there, I'm using this package in conjunction with data from Wikidata and I found that it does not handle responses with a `type.key` of `/type/redirect` as the user might expect it to, instead throwing a Zod error due to a missing `title` key.

### Reproduce
Call `book.get()` with an ID that leads to a redirect (like `OL15236127W`, which can be found on [Wikidata](https://www.wikidata.org/wiki/Q161531))

### Expected behavior
Package follows redirect to `location` and successfully returns the War and Peace edition `OL267171W`

### Actual behavior
Zod parse error due to response not satisfying the `Book` schema

### Addendum
I would have created a pull request, but seeing as this repository is a mirror, I thought it would be best to simply report the bug so it can be fixed upstream instead since I don't have a sourcehut account. If a pull request on this repository is acceptable I would be happy to do that instead!

**Comment by timharek** [comment]
Thanks for your issue! I see the problem, I wasn't aware of this kind of redirects, thanks for pointing it out.

I'm open to PRs here on GitHub, I will pull them upstream to SourceHut if I approve them. So if you want you can open up a PR and I'll review it :)

**Comment by timharek** [comment]
I saw it was a quickfix so I just fixed it, the fix is avaialbe in `v2.0.2`: https://jsr.io/@timharek/openlibrary@2.0.2

And thank you again for creating the issue!

**Comment by shayypy** [comment]
For reference this is how I've patched it temporarily in my project.
```typescript
async function getRequest(url: string | URL): Promise<unknown> {
  const result = await fetch(url, {
    method: "GET",
    headers: {
      Accept: "application/json",
      "User-Agent": userAgent,
    },
  })
    .then((response) =>
      response.json().then((_) => {
        const raw = _ as {
          location?: string;
          type?: { key: string };
        };
        if (raw.type?.key === "/type/redirect") {
          return getRequest(new URL(`${raw.location}.json`, API_URL));
        }
        return _;
      }),
    )
    .catch((error) => {
      console.log(error);
    });

  return result;
}
```
Not a super great solution but it's simple and generic so it should work for any request, not just `/works/:id.json`. One issue is that Open Library doesn't return the ID as a plain string so the client has to parse it out of `key` :/ (since it is now potentially different from the one that was requested). Also this is open to infinite recursion if there's a redirect ID that points to itself or something.

I also added my user-agent as a bit of flavor since Open Library [requests that clients do so](https://openlibrary.org/developers/api) :)

**Comment by shayypy** [comment]
Thanks! Sorry for the redundant comment, my web browser didn't show that you had replied until after I posted it.

**Comment by timharek** [comment]
No worries, good catch with the `User-Agent` – I forgot to add that, I just added it in `v2.0.3`.
